name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull juanssosa/apireservesaws:latest
    - name: Delete old docker container
      run: sudo docker rm -f apireservesaws-container || true
    - name: Run docker container
      run: sudo docker run -d -p 3000:3000 --name apireservesaws-container juanssosa/apireservesaws