name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login Dockerhub
      run: echo "{pass}" | docker login -u {user} --password-stdin
      
    - name: Build the Docker image
      run: docker build -t juanssosa/apireservesaws:latest .
    - name: Push to Dockerhub
      run: docker push juanssosa/apireservesaws:latest
